### ISSUE TITLE
(EXIT) no process: 

### ISSUE THREAD

**Issue by hudson2010** [DockYard/openid_connect#31]
iex(1)> OpenIDConnect.authorization_uri(:xero)
** (exit) exited in: GenServer.call(:openid_connect, {:discovery_document, :xero}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.10.2) lib/gen_server.ex:1013: GenServer.call/3
    (openid_connect 0.2.2) lib/openid_connect.ex:89: OpenIDConnect.authorization_uri/3
iex(1)>

**Comment by davydog187** [comment]
Fixed by #50
